import {randomUUID} from 'node:crypto';
import {type CharacterState,writeState} from '../../../packages/database/src/index.js';
import type pg from 'pg';
import {type World} from './world.js';
import {fail} from './gameplay.js';
export interface Trade{id:string;a:string;b:string;revision:number;offers:Record<string,{item:string|null;coins:string}>;confirmed:Set<string>;}
export class Social{
 parties=new Map<string,{leader:string;members:Set<string>;invites:Set<string>}>();trades=new Map<string,Trade>();blocks=new Map<string,Set<string>>();history:{actor:string;name:string;text:string;channel:string;party:string|null}[]=[];
 constructor(readonly world:World){}
 party(actor:string,target:string|undefined,value:string|undefined){const p=this.world.players.get(actor)!;if(value==='leave'){const group=p.party?this.parties.get(p.party):null;if(group){group.members.delete(actor);if(group.leader===actor)group.leader=[...group.members][0]??'';if(!group.members.size)this.parties.delete(p.party!);}p.party=null;return;}
 if(value==='accept'){const group=this.parties.get(target??'');if(!group?.invites.has(actor))fail('NO_INVITATION');if(group.members.size>=4||p.party)fail('PARTY_FULL');group.members.add(actor);group.invites.delete(actor);p.party=target!;return;}
 if(!target||!this.world.players.has(target)||target===actor)fail('PLAYER_NOT_FOUND');if(!p.party){p.party=randomUUID();this.parties.set(p.party,{leader:actor,members:new Set([actor]),invites:new Set()});}const group=this.parties.get(p.party)!;if(group.leader!==actor||group.members.size>=4)fail('PARTY_PERMISSION');group.invites.add(target);return{invited:target,party:p.party};}
 instance(actor:string){const p=this.world.players.get(actor)!;const id=p.party??randomUUID();if(p.party&&this.parties.get(p.party)?.leader!==actor)fail('PARTY_PERMISSION');const members=p.party?[...this.parties.get(p.party)!.members]:[actor];for(const member of members){const q=this.world.players.get(member);if(q){q.instance=id;q.motion.x=500;}}if(!this.world.monsters.some(m=>m.instance===id))for(let i=0;i<6;i++)this.world.monsters.push(this.world.makeMonster(p.state.map,id,i));return{id};}
 trade(actor:string,target:string|undefined,value:string|undefined){if(value==='invite'){if(!target||!this.world.players.has(target)||target===actor)fail('PLAYER_NOT_FOUND');const a=this.world.players.get(actor)!,b=this.world.players.get(target)!;if(a.state.map!==b.state.map||a.instance!==b.instance||Math.abs(a.motion.x-b.motion.x)>150)fail('TRADE_TOO_FAR');const t:Trade={id:randomUUID(),a:actor,b:target,revision:0,offers:{[actor]:{item:null,coins:'0'},[target]:{item:null,coins:'0'}},confirmed:new Set()};this.trades.set(t.id,t);return{id:t.id};}const trade=this.trades.get(target??'');if(!trade||![trade.a,trade.b].includes(actor))fail('TRADE_NOT_FOUND');if(value==='cancel'){this.trades.delete(trade.id);return;}if(value?.startsWith('offer:')){const item=value.slice(6);trade.offers[actor]={item:item||null,coins:'0'};trade.revision++;trade.confirmed.clear();}else if(value==='confirm')trade.confirmed.add(actor);return{trade,ready:trade.confirmed.size===2};}
 async exchange(actor:CharacterState,db:pg.PoolClient,t:Trade){if(t.confirmed.size!==2)fail('TRADE_UNCONFIRMED');const otherId=t.a===actor.id?t.b:t.a;const other=await db.query('SELECT state FROM characters WHERE id=$1 FOR UPDATE NOWAIT',[otherId]);const state=other.rows[0]?.state as CharacterState;if(!state)fail('PLAYER_NOT_FOUND');const p=this.world.players.get(actor.id),q=this.world.players.get(otherId);if(!p||!q||p.state.map!==q.state.map||p.instance!==q.instance||Math.abs(p.motion.x-q.motion.x)>150)fail('TRADE_TOO_FAR');const own=t.offers[actor.id]!.item,foreign=t.offers[otherId]!.item;const a=own?actor.inventory.find(i=>i.id===own):null,b=foreign?state.inventory.find(i=>i.id===foreign):null;if(own&&!a||foreign&&!b)fail('TRADE_ITEM_UNAVAILABLE');if(actor.inventory.length-(a?1:0)+(b?1:0)>40||state.inventory.length-(b?1:0)+(a?1:0)>40)fail('BAG_FULL');actor.inventory=actor.inventory.filter(i=>i.id!==own);state.inventory=state.inventory.filter(i=>i.id!==foreign);if(b)actor.inventory.push(b);if(a)state.inventory.push(a);await writeState(db,state);return{trade:t.id,other:otherId};}
 chat(actor:string,text:string,channel='map'){const p=this.world.players.get(actor)!;if(text.length>200||!text.trim())fail('INVALID_CHAT');if(channel==='party'&&!p.party)fail('NOT_IN_PARTY');const event={actor,name:p.state.name,text,channel,party:p.party};this.history.push(event);if(this.history.length>100)this.history.shift();return event;}
}
