import {randomUUID,randomInt} from 'node:crypto';
import {catalog} from '../../../packages/content/src/index.js';
import {stepMovement,resolveHit,durationTicks,adjustCost,applyShield,consumeShields,applyStatus,type MotionState,type Shield,type Status,type Element} from '../../../packages/simulation/src/index.js';
import type {CharacterState} from '../../../packages/database/src/state.js';
import {stats,bonus,boosted,fail} from './gameplay.js';
export interface Monster{id:string;map:string;instance:string;name:string;x:number;y:number;hp:bigint;maxHp:bigint;level:number;boss:boolean;respawn:number;owner:string|null;lastHit:number;statuses:Status[];}
export interface Player{state:CharacterState;epoch:number;motion:MotionState;seq:number;input:{axis:-1|0|1;jump:boolean};lastInput:number;instance:string;nextAttack:number;cooldowns:Map<string,number>;castUntil:number;shields:Shield[];party:string|null;board:{id:string;expires:number;x:number}|null;}
export class World{
 tick=0;players=new Map<string,Player>();monsters:Monster[]=[];events:{id:string;type:string;actor:string;target?:string;value?:string;x?:number;y?:number;tick:number}[]=[];
 onKill:(actor:string,monster:Monster,killId:string)=>void=()=>{};
 constructor(){for(const map of catalog.maps)for(let i=0;i<6;i++)this.monsters.push(this.makeMonster(map.id,'public',i));}
 makeMonster(map:string,instance:string,i:number):Monster{const m=catalog.maps.find(m=>m.id===map)!;const boss=i===5&&!m.safe;const maxHp=BigInt(100+m.minLevel*35)*(boss?12n:1n);return{id:randomUUID(),map,instance,name:boss?'Hộ Giới Linh Thú':['Trúc Yêu','Linh Lang','Thạch Quái'][i%3]!,x:700+i*260,y:420,hp:maxHp,maxHp,level:m.minLevel,boss,respawn:0,owner:null,lastHit:0,statuses:[]};}
 add(state:CharacterState,epoch:number){const old=this.players.get(state.id);this.players.set(state.id,{state,epoch,motion:old?.motion??{x:state.x,y:state.y,vx:0,vy:0,grounded:true},seq:old?.seq??-1,input:{axis:0,jump:false},lastInput:this.tick,instance:old?.instance??'public',nextAttack:old?.nextAttack??0,cooldowns:old?.cooldowns??new Map(),castUntil:old?.castUntil??0,shields:old?.shields??[],party:old?.party??null,board:old?.board??null});}
 input(id:string,input:{seq:number;axis:-1|0|1;jump:boolean}){const p=this.players.get(id);if(!p||input.seq<=p.seq)return;p.seq=input.seq;p.input={axis:input.axis,jump:input.jump};p.lastInput=this.tick;}
 sync(id:string,state:CharacterState){const p=this.players.get(id);if(!p)return;const mapChanged=p.state.map!==state.map;p.state=state;if(mapChanged){p.motion={x:state.x,y:420,vx:0,vy:0,grounded:true};p.input={axis:0,jump:false};p.instance='public';}}
 event(type:string,actor:string,target?:string,value?:string,x?:number,y?:number){this.events.push({id:randomUUID(),type,actor,target,value,x,y,tick:this.tick});if(this.events.length>100)this.events.shift();}
 targets(p:Player,range=800){return this.monsters.filter(m=>m.map===p.state.map&&m.instance===p.instance&&m.hp>0n&&Math.abs(m.x-p.motion.x)<=range).sort((a,b)=>Math.abs(a.x-p.motion.x)-Math.abs(b.x-p.motion.x));}
 attack(id:string,targetId?:string,skillId?:string){const p=this.players.get(id);if(!p||BigInt(p.state.hp)===0n||this.tick<p.nextAttack||this.tick<p.castUntil)return;const st=stats(p.state);const skill=skillId?catalog.skills.find(k=>k.id===skillId):undefined;if(skillId&&(!skill||!p.state.skills.includes(skillId)||skill.branch!==p.state.branch))fail('SKILL_NOT_LEARNED');if(skill&&(p.cooldowns.get(skill.id)??0)>this.tick)fail('COOLDOWN');const range=skill?.range??130;const targets=this.targets(p,range);let target=targetId?targets.find(t=>t.id===targetId):targets[0];if(skill&&['shield','defense','dash'].includes(skill.effect)){target=undefined;}else if(!target)fail('TARGET_OUT_OF_RANGE');if(skill){const mana=adjustCost(BigInt(skill.mana),bonus(p.state,'manaReduction'));if(BigInt(p.state.mp)<mana)fail('NOT_ENOUGH_MP');p.state.mp=(BigInt(p.state.mp)-mana).toString();p.cooldowns.set(skill.id,this.tick+Math.max(1,Math.ceil(skill.cooldown*(10000-Math.min(9900,bonus(p.state,'cooldownReduction')))/10000)));p.castUntil=this.tick+skill.castTicks;}
 p.nextAttack=this.tick+durationTicks(16,bonus(p.state,'attackSpeed'));
 if(skill?.effect==='dash'){const map=catalog.maps.find(m=>m.id===p.state.map)!;p.motion.x=Math.max(16,Math.min(map.width-16,p.motion.x+180));this.event('dash',id);return;}
 if(skill&&['shield','defense'].includes(skill.effect)){p.shields=applyShield(p.shields,{source:skill.id,caster:id,amount:boosted(p.state,st.maxHp/3n,'shield'),expires:this.tick+200});this.event('shield',id,undefined,st.maxHp.toString());return;}
 if(!target)return;const list=skill&&['aoe','fusion','multi'].includes(skill.effect)?targets.slice(0,skill.effect==='multi'?3:8):[target];
 for(const m of list){if(m.owner&&m.owner!==id&&m.lastHit+300>this.tick&&!m.boss){const owner=this.players.get(m.owner);if(!p.party||p.party!==owner?.party)continue;}m.owner??=id;m.lastHit=this.tick;const map=catalog.maps.find(x=>x.id===m.map)!;let raw=st.attack*BigInt(skill?.damageBps??10000)/10000n;if(p.board&&p.board.expires>this.tick&&catalog.boards.find(b=>b.id===p.board!.id)?.effect==='attack')raw=raw*BigInt(11500+bonus(p.state,'board'))/10000n;
 const elements:Element[]=skill?.effect==='fusion'?['metal','wood','water','fire','earth']:[(skill?.element==='weapon'||!skill?st.weaponElement:skill.element) as Element];let total=0n;for(const [index,element]of elements.entries()){const part=raw/BigInt(elements.length)+(index===0?raw%BigInt(elements.length):0n);const r=resolveHit({raw:part,level:p.state.level,defense:BigInt(m.level*2),hp:m.hp,shield:0n,attackElement:element,bodyElement:map.element as Element,crit:randomInt(10000)<st.crit,lifestealBps:st.lifesteal,reductionBps:0});m.hp-=r.hpDamage;total+=r.hpDamage;p.state.hp=(BigInt(p.state.hp)+r.lifesteal>st.maxHp?st.maxHp:BigInt(p.state.hp)+r.lifesteal).toString();}
 if(skill?.effect==='slow'||skill?.effect==='root')m.statuses=applyStatus(m.statuses,{kind:skill.effect,expires:this.tick+60},m.boss);this.event('hit',id,m.id,total.toString(),m.x,m.y-70);if(m.hp===0n){m.respawn=this.tick+(m.boss?1200:160);const killId=randomUUID();this.onKill(id,m,killId);this.event('kill',id,m.id);} }
 }
 step(){this.tick++;for(const p of this.players.values()){const map=catalog.maps.find(m=>m.id===p.state.map)!;if(this.tick-p.lastInput>20)p.input={axis:0,jump:false};p.motion=stepMovement(p.motion,p.input,map,0.05);p.input.jump=false;p.state.x=p.motion.x;p.state.y=p.motion.y;if(p.state.auto&&this.tick%4===0){const target=this.targets(p,800)[0];if(target){if(Math.abs(target.x-p.motion.x)>100)p.input.axis=target.x>p.motion.x?1:-1;else{p.input.axis=0;try{const skill=p.state.loadout.find(id=>(p.cooldowns.get(id)??0)<=this.tick&&catalog.skills.find(k=>k.id===id)?.branch===p.state.branch);this.attack(p.state.id,target.id,skill);}catch{try{this.attack(p.state.id,target.id);}catch{}}}}}
 if(this.tick%20===0){const st=stats(p.state);p.state.mp=(BigInt(p.state.mp)+3n>st.maxMp?st.maxMp:BigInt(p.state.mp)+3n).toString();if(map.safe)p.state.hp=(BigInt(p.state.hp)+st.maxHp/20n>st.maxHp?st.maxHp:BigInt(p.state.hp)+st.maxHp/20n).toString();}
 }
 for(const m of this.monsters){m.statuses=m.statuses.filter(s=>s.expires>this.tick);if(m.hp===0n){if(this.tick>=m.respawn){m.hp=m.maxHp;m.owner=null;}continue;}if(m.owner&&this.tick-m.lastHit>300)m.owner=null;if(this.tick%40!==0)continue;const target=[...this.players.values()].find(p=>p.state.map===m.map&&p.instance===m.instance&&Math.abs(p.motion.x-m.x)<100);if(!target||catalog.maps.find(x=>x.id===m.map)?.safe||m.statuses.some(s=>['stun','freeze'].includes(s.kind)))continue;const st=stats(target.state);const r=resolveHit({raw:BigInt(m.level*4+8),level:m.level,defense:st.defense,hp:BigInt(target.state.hp),shield:target.shields.reduce((n,s)=>n+s.amount,0n),attackElement:'physical',bodyElement:st.bodyElement,crit:false,reflectBps:st.reflection,reductionBps:bonus(target.state,'resistance')});target.shields=consumeShields(target.shields,r.damage,this.tick).layers;target.state.hp=(BigInt(target.state.hp)-r.hpDamage).toString();m.hp=m.hp>r.reflection?m.hp-r.reflection:0n;this.event('hurt',target.state.id,m.id,r.hpDamage.toString());if(target.state.hp==='0'){target.motion.x=320;target.state.map='map-0';target.state.hp=st.maxHp.toString();target.state.auto=false;this.event('death',target.state.id);} }
 }
 snapshot(id:string){const p=this.players.get(id)!;return{type:'snapshot',version:1,contentVersion:catalog.balance.version,tick:this.tick,epoch:p.epoch,ack:p.seq,you:p.state,stats:stats(p.state),instance:p.instance,cooldowns:Object.fromEntries(p.cooldowns),players:[...this.players.values()].filter(q=>q.state.map===p.state.map&&q.instance===p.instance&&Math.abs(q.motion.x-p.motion.x)<=800).map(q=>({id:q.state.id,name:q.state.name,branch:q.state.branch,level:q.state.level,x:q.motion.x,y:q.motion.y,hp:q.state.hp})),monsters:this.monsters.filter(m=>m.map===p.state.map&&m.instance===p.instance&&Math.abs(m.x-p.motion.x)<=800).map(m=>({...m,hp:m.hp.toString(),maxHp:m.maxHp.toString()})),events:this.events.filter(e=>this.tick-e.tick<20&&this.players.get(e.actor)?.instance===p.instance)};}
}
